# This file has been generated by node2nix 1.5.1. Do not edit!

{pkgs ? import <nixpkgs> {
    inherit system;
  }, system ? builtins.currentSystem, nodejs ? pkgs."nodejs-6_x"}:

let
  nodeEnv = import ./node-env.nix {
    inherit (pkgs) stdenv python2 utillinux runCommand writeTextFile;
    inherit nodejs;
  };
  nodePackages = import ./node-packages.nix {
    inherit (pkgs) fetchurl fetchgit;
    inherit nodeEnv;
    globalBuildInputs = with pkgs; [
      nodePackages_6_x.node-pre-gyp electron chromedriver
    ];
  };
in
{
  electron = nodePackages."electron-1.7.11".override (oldAttrs: {
    preRebuild = ''
      ln -sT ${pkgs.electron}/lib/electron dist
      echo -n dist/electron > path.txt
    '';
  });
  electron-chromedriver = nodePackages."electron-chromedriver-1.7.1".override (oldAttrs: {
    preRebuild = ''
      mkdir bin
      ln -s ${pkgs.chromedriver}/bin/chromedriver bin/chromedriver
    '';
    dontNpmInstall = true;
  });
}
