# This file has been generated by node2nix 1.5.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {};
  args = {
    name = "daedalus";
    packageName = "daedalus";
    version = "1.5.1";
    src = ./..;
    buildInputs = globalBuildInputs;
    meta = {
      description = "Cryptocurrency Wallet";
    };
    production = true;
    bypassCache = false;
  };
in
{
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
}